generator:
  nlabels: 1
  conditioning: unconditional
discriminator:
  nlabels: 1
  conditioning: unconditional
inherit_from: configs/imagenet/default.yaml
training:
  out_dir: output/pretrained/imagenet/unconditional
pretrained:
  model: http://selfcondgan.csail.mit.edu/weights/uncondgan_i_model.pt
